version: "3.8"

services:
  web:
    build: .
    ports:
      - "5050:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=visitor_counter
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

